"""Per-part code generation endpoint (Stage 4). Returns CodeGenResponse (result XOR refusal).

Known families build from exact deterministic templates; any other part is generated by the LLM
(validator-gated) so the product can build arbitrary shapes, not a fixed family list.
"""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel

from ..models import CodeGenRequest, CodeGenResponse, ObjectPlan
from ..services.codegen import get_codegen_service

router = APIRouter(prefix="/api/codegen", tags=["CodeGen"])


class EditRequest(BaseModel):
    """A natural-language edit to a part's parametric dimensions (ADR-016)."""

    object_plan: ObjectPlan
    part_id: str
    text: str
    dimensions: dict[str, float] = {}


# the closed grammar the LLM edit must speak — dims (op over a known hole) + a texture pattern (a
# motif name or a sandboxed h(u,v) expression) + edge features. Validated again server-side, so the
# model can never emit an unsafe operation.
_EDIT_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "properties": {
        "dimensions": {"type": "array", "items": {
            "type": "object", "additionalProperties": False,
            "properties": {"hole": {"type": "string"},
                           "op": {"type": "string", "enum": ["set", "scale", "delta"]},
                           "value": {"type": "number"}},
            "required": ["hole", "op", "value"]}},
        "pattern": {"type": "string"},
        "add_features": {"type": "array", "items": {"type": "string"}},
        "message": {"type": "string"},
    },
    "required": ["dimensions", "pattern", "add_features", "message"],
}

_EDIT_SYSTEM = (
    "You edit ONE parametric CAD part. Return ONLY the structured change. 'Holes' are the part's "
    "editable dimensions in millimetres. dimensions = [{hole, op, value}] where op is set (absolute "
    "mm), scale (a multiplier, e.g. 1.2), or delta (+/- mm); use ONLY the listed hole names. pattern "
    "= a surface-texture motif name (scales | knurl | studs | ribs | rings | grooves | hex | weave | "
    "bumps) OR a height-field expression h(u,v) in [0,1] for any custom pattern, using sin cos tan "
    "sqrt abs floor frac tri saw noise hash min max pow clamp smoothstep step mix sign + - * / %% ** "
    "and pi/tau (u,v in [0,1] over the wall; cols,rows tile it). WHENEVER the edit mentions the "
    "surface look/texture you MUST set `pattern` — never just describe it in the message. Examples: "
    "'diagonal wave' -> '0.5+0.5*sin((u*cols+v*rows)*tau)'; 'wavy ripples' -> '0.5+0.5*sin(v*rows*tau*2)'; "
    "'knurled' -> 'knurl'; 'spiky downward' -> 'pow(1-frac(v*rows),3)*(1-abs(2*frac(u*cols)-1))'. Use "
    "'' for pattern ONLY when the texture is unchanged. add_features = any of ['fillet','chamfer'] to "
    "round or bevel the edges. Make the smallest change that satisfies the request; message = one short "
    "line of what you changed."
)


async def _llm_edit(text: str, genome, part):
    """Open-ended edit: let the model interpret ANY phrasing into the closed edit grammar. Returns an
    EditResult, or None if no real LLM is configured / the call fails (caller falls back)."""
    from ..gateway import Message, sanitize_schema
    from ..services.genome.edit import edit_result_from_llm, parameters
    from ..services.intent import get_intent_service

    gateway = get_intent_service()._gateway
    profile = "INTENT"
    if gateway.profiles.get(profile, {}).get("provider", "mock") == "mock":
        return None  # no live model -> deterministic path
    vals = {k.split(".", 1)[1]: round(v, 3) for k, v in parameters(genome).items()}
    user = (f"Holes (current mm): {vals}\nCurrent texture pattern: "
            f"{(getattr(part, 'pattern', '') or 'none')}\n"
            f"Existing features: {list(getattr(part, 'features', []))}\nUser edit: \"{text}\"")
    try:
        res = await gateway.generate_structured(
            [Message("system", _EDIT_SYSTEM), Message("user", user)],
            sanitize_schema(_EDIT_SCHEMA), profile=profile, n=1)
    except Exception:  # noqa: BLE001 - any gateway failure -> fall back to deterministic
        return None
    return edit_result_from_llm(res.candidates[0], genome) if res.candidates else None


@router.post("/generate", response_model=CodeGenResponse)
async def generate_code(request: CodeGenRequest) -> CodeGenResponse:
    # For a novel part the sketch stage already generated the parametric IR; the palette sends it
    # back as drawing_data.base_ir so we only substitute the user's dimensions (no second model call).
    base_ir = (request.drawing_data or {}).get("base_ir")
    return await get_codegen_service().generate(
        request.object_plan, request.part_id, request.dimensions, base_ir=base_ir
    )


@router.post("/assembly")
async def assembly_certificate(object_plan: ObjectPlan) -> dict:
    """Object-level proof-of-fitness (ADR-014): the WHOLE object's typed interfaces mate, every part
    is connected, and the assembly is rigid. Deterministic (no LLM) and independently re-checkable
    (genome.certificate.recheck). The palette can call this after building all the parts."""
    from ..services.genome.assembly import certify_assembly

    return certify_assembly(object_plan).to_dict()


@router.post("/edit")
async def edit_part(request: EditRequest) -> dict:
    """Apply a natural-language edit to a part (ADR-016) — NOT just dimensions: also surface texture
    (relief / density / a different motif or a custom function) and geometry (round / bevel the
    edges). Bidirectional + reference-safe: the returned dimensions keep the SAME user-parameter
    names, so nothing downstream breaks. Returns the new dimensions + (changed) pattern + features for
    the palette to apply and rebuild."""
    from ..services import placeholder
    from ..services.codegen import _holes_from_dimensions
    from ..services.genome import plan_genome
    from ..services.genome.edit import apply_edit, interpret_edit
    from ..services.genome.library import build_ir
    from ..services.genome.solver import solve

    part = placeholder._find_part(request.object_plan, request.part_id)
    if part is None:
        return {"edited": False, "reason": "no such part", "dimensions": request.dimensions}
    genome = plan_genome(part)
    if genome is None:
        return {"edited": False, "reason": "part is not parametrically editable",
                "dimensions": request.dimensions}

    # OPEN-ENDED: the LLM interprets ANY edit; the deterministic interpreter fills what it reliably
    # under-emits (the texture pattern / edge fillets), so texture edits work even when the model only
    # describes them. LLM wins on the rest; deterministic is the full fallback.
    from dataclasses import replace

    deterministic = interpret_edit(request.text, genome, part)
    result = await _llm_edit(request.text, genome, part)
    if result is None or result.empty:
        result = deterministic
    else:
        if result.pattern is None and deterministic.pattern is not None:
            result = replace(result, pattern=deterministic.pattern)
        if not result.add_features and deterministic.add_features:
            result = replace(result, add_features=deterministic.add_features)
        if not result.dim_edits and deterministic.dim_edits:
            result = replace(result, dim_edits=deterministic.dim_edits)
    if result.empty:
        return {"edited": False, "dimensions": request.dimensions,
                "message": "couldn't interpret that edit"}

    # a texture/geometry change re-plans the part (new pattern / added fillet|chamfer); dimensions
    # then apply on top. Everything keeps the same user-parameter names -> references hold.
    new_pattern = result.pattern if result.pattern is not None else getattr(part, "pattern", "")
    new_features = list(getattr(part, "features", []))
    for f in result.add_features:
        if f not in new_features:
            new_features.append(f)
    part2 = part.model_copy(update={"pattern": new_pattern, "features": new_features})

    g2 = plan_genome(part2) or genome
    solved, _ = solve(g2, _holes_from_dimensions(part.id, request.dimensions))
    for e in result.dim_edits:
        solved = apply_edit(solved, e)
    ir, _ = build_ir(solved)
    dims = {c.params["name"]: c.params["value"] for c in ir.commands
            if c.type.value == "CREATE_USER_PARAMETER"}
    return {"edited": True, "dimensions": dims, "pattern": part2.pattern,
            "features": new_features, "message": result.note}
